<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinCore.Account.Application\FinCore.Account.Application.csproj" />
    <ProjectReference Include="..\FinCore.Account.Infrastructure\FinCore.Account.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\FinCore.BuildingBlocks\FinCore.BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
